- name: "SCORED | 5.1.1 | PATCH | Ensure cron daemon is enabled"
  service:
    name: crond
    enabled: yes
  when:
    - rhel8cis_rule_5_1_1|bool
  tags:
    - level1
    - level2
    - patch
    - rule_5.1.1

- name: "SCORED | 5.1.2 | PATCH | Ensure permissions on /etc/crontab are configured"
  file:
    dest: /etc/crontab
    owner: root
    group: root
    mode: 0600
  when:
    - rhel8cis_rule_5_1_2|bool
  tags:
    - level1
    - level2
    - patch
    - rule_5.1.2

- name: "SCORED | 5.1.3 | PATCH | Ensure permissions on /etc/cron.hourly are configured"
  file:
    dest: /etc/cron.hourly
    state: directory
    owner: root
    group: root
    mode: 0700
  when:
    - rhel8cis_rule_5_1_3|bool
  tags:
    - level1
    - level2
    - patch
    - rule_5.1.3

- name: "SCORED | 5.1.4 | PATCH | Ensure permissions on /etc/cron.daily are configured"
  file:
    dest: /etc/cron.daily
    state: directory
    owner: root
    group: root
    mode: 0700
  when:
    - rhel8cis_rule_5_1_4|bool
  tags:
    - level1
    - level2
    - patch
    - rule_5.1.4

- name: "SCORED | 5.1.5 | PATCH | Ensure permissions on /etc/cron.weekly are configured"
  file:
    dest: /etc/cron.weekly
    state: directory
    owner: root
    group: root
    mode: 0700
  when:
    - rhel8cis_rule_5_1_5|bool
  tags:
    - level1
    - level2
    - patch
    - rule_5.1.5

- name: "SCORED | 5.1.6 | PATCH | Ensure permissions on /etc/cron.monthly are configured"
  file:
    dest: /etc/cron.monthly
    state: directory
    owner: root
    group: root
    mode: 0700
  when:
    - rhel8cis_rule_5_1_6|bool
  tags:
    - level1
    - level2
    - patch
    - rule_5.1.6

- name: "SCORED | 5.1.7 | PATCH | Ensure permissions on /etc/cron.d are configured"
  file:
    dest: /etc/cron.d
    state: directory
    owner: root
    group: root
    mode: 0700
  when:
    - rhel8cis_rule_5_1_7|bool
  tags:
    - level1
    - level2
    - patch
    - rule_5.1.7

- name: "SCORED | 5.1.8 | PATCH | Ensure at/cron is restricted to authorized users"
  block:
    - name: "SCORED | 5.1.8 | PATCH | Ensure at/cron is restricted to authorized users"
      file:
        dest: /etc/at.deny
        state: absent

    - name: "SCORED | 5.1.8 | PATCH | Check if at.allow exists"
      stat:
        path: "/etc/at.allow"
      register: p

    - name: "SCORED | 5.1.8 | PATCH | Ensure at/cron is restricted to authorized users"
      file:
        dest: /etc/at.allow
        state: '{{ "file" if  p.stat.exists else "touch" }}'
        owner: root
        group: root
        mode: 0600

    - name: "SCORED | 5.1.8 | PATCH | Ensure at/cron is restricted to authorized users"
      file:
        dest: /etc/cron.deny
        state: absent

    - name: "SCORED | 5.1.8 | PATCH | Check if cron.allow exists"
      stat:
        path: "/etc/cron.allow"
      register: p

    - name: "SCORED | 5.1.8 | PATCH | Ensure at/cron is restricted to authorized users"
      file:
        dest: /etc/cron.allow
        state: '{{ "file" if  p.stat.exists else "touch" }}'
        owner: root
        group: root
        mode: 0600
  when:
      - rhel8cis_rule_5_1_8|bool
  tags:
      - level1
      - level2
      - patch
      - rule_5.1.8

#- name: "CI | 5.2 | PATCH | Ensure host keys are present."
#  command: /usr/bin/ssh-keygen -A
#  args:
#    creates: /etc/ssh/ssh_host_ed25519_key

- name: "SCORED | 5.2.1 | PATCH | Ensure permissions on /etc/ssh/sshd_config are configured"
  file:
    dest: /etc/ssh/sshd_config
    state: file
    owner: root
    group: root
    mode: 0600
  when:
    - rhel8cis_rule_5_2_1|bool
  tags:
    - level1
    - level2
    - patch
    - rule_5.2.1

- name: "SCORED | 5.2.2 | PATCH | Ensure SSH access is limited"
  block:
    - name: "SCORED | 5.2.2 | PATCH | Ensure SSH access is limited - allowusers"
      lineinfile:
        state: present
        dest: /etc/ssh/sshd_config
        regexp: "(?i)^AllowUsers"
        line: AllowUsers {{ rhel8cis_sshd['allowusers'] }}
        validate: /usr/sbin/sshd -t -f %s
      notify:
        - restart sshd
      when:
        - rhel8cis_sshd['allowusers'] | default('')

    - name: "SCORED | 5.2.2 | PATCH | Ensure SSH access is limited - allowgroups"
      lineinfile:
        state: present
        dest: /etc/ssh/sshd_config
        regexp: "(?i)^AllowGroups"
        line: AllowGroups {{ rhel8cis_sshd['allowgroups'] }}
        validate: /usr/sbin/sshd -t -f %s
      notify:
        - restart sshd
      when:
        - rhel8cis_sshd['allowgroups'] | default('')

    - name: "SCORED | 5.2.2 | PATCH | Ensure SSH access is limited - denyusers"
      lineinfile:
        state: present
        dest: /etc/ssh/sshd_config
        regexp: "(?i)^DenyUsers"
        line: DenyUsers {{ rhel8cis_sshd['denyusers'] }}
        validate: /usr/sbin/sshd -t -f %s
      notify:
        - restart sshd
      when:
        - rhel8cis_sshd['denyusers'] | default('')

    - name: "SCORED | 5.2.2 | PATCH | Ensure SSH access is limited - denygroups"
      lineinfile:
        state: present
        dest: /etc/ssh/sshd_config
        regexp: "(?i)^DenyGroups"
        line: DenyGroups {{ rhel8cis_sshd['denygroups'] }}
        validate: /usr/sbin/sshd -t -f %s
      notify:
        - restart sshd
      when:
        - rhel8cis_sshd['denygroups'] | default('')
  when:
      - rhel8cis_rule_5_2_2|bool
  tags:
      - level1
      - level2
      - patch
      - rule_5.2.2

- name: "SCORED | 5.2.3 | PATCH | Ensure permissions on SSH private host key files are configured"
  shell: |
    find /etc/ssh -xdev -type f -name 'ssh_host_*_key' -exec chown root:root {} \;
    find /etc/ssh -xdev -type f -name 'ssh_host_*_key' -exec chmod 0600 {} \;
  when:
    - rhel8cis_rule_5_2_3|bool
  tags:
    - level1
    - level2
    - patch
    - rule_5.2.3

- name: "SCORED | 5.2.4 | PATCH | Ensure permissions on SSH public host key files are configured"
  shell: |
    find /etc/ssh -xdev -type f -name 'ssh_host_*_key.pub' -exec chown root:root {} \;
    find /etc/ssh -xdev -type f -name 'ssh_host_*_key.pub' -exec chmod 0644 {} \;
  when:
    - rhel8cis_rule_5_2_4|bool
  tags:
    - level1
    - level2
    - patch
    - rule_5.2.4

- name: "SCORED | 5.2.5 | PATCH | Ensure SSH LogLevel is set to INFO"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '(?i)^LogLevel'
    line: 'LogLevel INFO'
    validate: /usr/sbin/sshd -t -f %s
  when:
    - rhel8cis_rule_5_2_5|bool
  notify: restart sshd
  tags:
    - level1
    - level2
    - patch
    - rule_5.2.5

- name: "SCORED | 5.2.6 | PATCH | Ensure SSH X11 forwarding is disabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '(?i)^X11Forwarding'
    line: 'X11Forwarding no'
    validate: /usr/sbin/sshd -t -f %s
  when:
    - rhel8cis_rule_5_2_6|bool
  notify: restart sshd
  tags:
    - level1
    - level2
    - patch
    - rule_5.2.6

- name: "SCORED | 5.2.7 | PATCH | Ensure SSH MaxAuthTries is set to 4 or less"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '(?i)^(#)?MaxAuthTries \d'
    line: 'MaxAuthTries 4'
    validate: /usr/sbin/sshd -t -f %s
  when:
    - rhel8cis_rule_5_2_7|bool
  notify: restart sshd
  tags:
    - level1
    - level2
    - patch
    - rule_5.2.7

- name: "SCORED | 5.2.8 | PATCH | Ensure SSH IgnoreRhosts is enabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '(?i)^IgnoreRhosts'
    line: 'IgnoreRhosts yes'
    validate: /usr/sbin/sshd -t -f %s
  when:
    - rhel8cis_rule_5_2_8|bool
  notify: restart sshd
  tags:
    - level1
    - level2
    - patch
    - rule_5.2.8

- name: "SCORED | 5.2.9 | PATCH | Ensure SSH HostbasedAuthentication is disabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '(?i)^HostbasedAuthentication'
    line: 'HostbasedAuthentication no'
    validate: /usr/sbin/sshd -t -f %s
  when:
    - rhel8cis_rule_5_2_9|bool
  notify: restart sshd
  tags:
    - level1
    - level2
    - patch
    - rule_5.2.9

- name: "SCORED | 5.2.10 | PATCH | Ensure SSH root login is disabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '(?i)^PermitRootLogin'
    line: 'PermitRootLogin no'
    validate: /usr/sbin/sshd -t -f %s
  when:
    - rhel8cis_rule_5_2_10|bool
  notify: restart sshd
  tags:
    - level1
    - level2
    - patch
    - rule_5.2.10

- name: "SCORED | 5.2.11 | PATCH | Ensure SSH PermitEmptyPasswords is disabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '(?i)^PermitEmptyPasswords'
    line: 'PermitEmptyPasswords no'
    validate: /usr/sbin/sshd -t -f %s
  when:
    - rhel8cis_rule_5_2_11|bool
  notify: restart sshd
  tags:
    - level1
    - level2
    - patch
    - rule_5.2.11

- name: "SCORED | 5.2.12 | PATCH | Ensure SSH PermitUserEnvironment is disabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '(?i)^PermitUserEnvironment'
    line: 'PermitUserEnvironment no'
    validate: /usr/sbin/sshd -t -f %s
  when:
    - rhel8cis_rule_5_2_12|bool
  notify: restart sshd
  tags:
    - level1
    - level2
    - patch
    - rule_5.2.12

- name: "SCORED | 5.2.13 | PATCH | Ensure SSH Idle Timeout Interval is configured"
  block:
    - name: "SCORED | 5.2.13 | PATCH | Ensure SSH Idle Timeout Interval is configured"
      lineinfile:
        state: present
        dest: /etc/ssh/sshd_config
        regexp: '(?i)^ClientAliveInterval'
        line: "ClientAliveInterval {{ rhel8cis_sshd['clientaliveinterval'] }}"
        validate: /usr/sbin/sshd -t -f %s
      notify: restart sshd

    - name: "SCORED | 5.2.13 | PATCH | Ensure SSH ClientAliveCountMax set to <= 3"
      lineinfile:
        state: present
        dest: /etc/ssh/sshd_config
        regexp: '(?i)^ClientAliveCountMax'
        line: "ClientAliveCountMax {{ rhel8cis_sshd['clientalivecountmax'] }}"
        validate: /usr/sbin/sshd -t -f %s
      notify: restart sshd
  when:
      - rhel8cis_rule_5_2_13|bool
  tags:
      - level1
      - level2
      - patch
      - rule_5.2.13

- name: "SCORED | 5.2.14 | PATCH | Ensure SSH LoginGraceTime is set to one minute or less"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '(?i)^LoginGraceTime'
    line: "LoginGraceTime {{ rhel8cis_sshd['logingracetime'] }}"
    validate: /usr/sbin/sshd -t -f %s
  when:
    - rhel8cis_rule_5_2_14|bool
  notify: restart sshd
  tags:
    - level1
    - level2
    - patch
    - rule_5.2.14

- name: "SCORED | 5.2.15 | PATCH | Ensure SSH warning banner is configured"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '(?i)^Banner'
    line: 'Banner /etc/issue.net'
    validate: /usr/sbin/sshd -t -f %s
  when:
    - rhel8cis_rule_5_2_15|bool
  notify: restart sshd
  tags:
    - level1
    - level2
    - patch
    - rule_5.2.15

- name: "SCORED | 5.2.16 | PATCH | Ensure SSH PAM is enabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '(?i)^UsePAM'
    line: 'UsePAM yes'
    validate: /usr/sbin/sshd -t -f %s
  when:
    - rhel8cis_rule_5_2_16|bool
  notify: restart sshd
  tags:
    - level1
    - level2
    - patch
    - rule_5.2.16

- name: "SCORED | 5.2.17 | PATCH | Ensure SSH AllowTcpForwarding is disabled"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '(?i)^AllowTcpForwarding'
    line: 'AllowTcpForwarding no'
    validate: /usr/sbin/sshd -t -f %s
  when:
    - rhel8cis_rule_5_2_17|bool
  notify: restart sshd
  tags:
    - level1
    - level2
    - patch
    - rule_5.2.17

- name: "SCORED | 5.2.18 | PATCH | Ensure SSH MaxStartups is configured"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '(?i)^MaxStartups'
    line: 'MaxStartups 10:30:60'
    validate: /usr/sbin/sshd -t -f %s
  when:
    - rhel8cis_rule_5_2_18|bool
  notify: restart sshd
  tags:
    - level1
    - level2
    - patch
    - rule_5.2.18

- name: "SCORED | 5.2.19 | PATCH | Ensure SSH MaxSessions is set to 4 or less"
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: '(?i)^MaxSessions'
    line: 'MaxSessions 4'
    validate: /usr/sbin/sshd -t -f %s
  when:
    - rhel8cis_rule_5_2_19|bool
  notify: restart sshd
  tags:
    - level1
    - level2
    - patch
    - rule_5.2.19

- name: "SCORED | 5.2.20 | PATCH | Ensure system-wide crypto policy is not over-ridden"
  lineinfile:
    state: absent
    dest: /etc/ssh/sshd_config
    regexp: '(?i)^CRYPTO_POLICY'
    validate: /usr/sbin/sshd -t -f %s
  when:
    - rhel8cis_rule_5_2_20|bool
  notify: restart sshd
  tags:
    - level1
    - level2
    - patch
    - rule_5.2.20

- name: "SCORED | 5.4.1 | PATCH | Ensure password creation requirements are configured"
  lineinfile:
    state: present
    dest: /etc/security/pwquality.conf
    regexp: ^{{ item.key }}[ =]
    line: '{{ item.key }} = {{ item.value }}'
  with_dict: "{{ rhel8cis_pwquality }}"
  when:
    - rhel8cis_rule_5_4_1|bool
  tags:
    - level1 
    - level2
    - patch
    - rule_5.4.1

- name: "SCORED | 5.4.2 | PATCH | Ensure lockout for failed password attempts is configured"
  command: /bin/true
  changed_when: no
  when:
    - rhel8cis_rule_5_4_2|bool
  tags:
    - level1
    - level2
    - patch
    - rule_5.4.2
    - notimplemented

- name: "SCORED | 5.4.3 | PATCH | Ensure password reuse is limited"
  command: /bin/true
  changed_when: no
  when:
    - rhel8cis_rule_5_4_3|bool
  tags:
    - level1
    - level2
    - patch
    - rule_5.4.3
    - notimplemented

- name: "SCORED | 5.4.4 | PATCH | Ensure password hashing algorithm is SHA-512"
  command: /bin/true
  changed_when: no
  failed_when: no
  when:
      - rhel8cis_rule_5_4_4|bool
  tags:
      - level1
      - level2
      - patch
      - rule_5.4.4

- name: "SCORED | 5.5.1.1 | PATCH | Ensure password expiration is 365 days or less"
  lineinfile:
    state: present
    dest: /etc/login.defs
    regexp: '^PASS_MAX_DAYS'
    line: "PASS_MAX_DAYS {{ rhel8cis_pass['max_days'] }}"
  when:
    - rhel8cis_rule_5_5_1_1|bool
  tags:
    - level1
    - level2
    - patch
    - rule_5.5.1.1

- name: "SCORED | 5.5.1.2 | PATCH | Ensure minimum days between password changes is 7 or more"
  lineinfile:
    state: present
    dest: /etc/login.defs
    regexp: '^PASS_MIN_DAYS'
    line: "PASS_MIN_DAYS {{ rhel8cis_pass['min_days'] }}"
  when:
    - rhel8cis_rule_5_5_1_2|bool
  tags:
    - level1
    - level2
    - patch
    - rule_5.5.1.2

- name: "SCORED | 5.5.1.3 | PATCH | Ensure password expiration warning days is 7 or more"
  lineinfile:
    state: present
    dest: /etc/login.defs
    regexp: '^PASS_WARN_AGE'
    line: "PASS_WARN_AGE {{ rhel8cis_pass['warn_age'] }}"
  when:
    - rhel8cis_rule_5_5_1_3|bool
  tags:
    - level1
    - level2
    - patch
    - rule_5.5.1.3

- name: "SCORED | 5.5.1.4 | PATCH | Ensure inactive password lock is 30 days or less"
  command: /bin/true
  changed_when: no
  when:
    - rhel8cis_rule_5_5_1_4|bool
  tags:
    - level1
    - level2
    - patch
    - rule_5.5.1.4
    - notimplemented

- name: "SCORED | 5.5.2 | PATCH | Ensure system accounts are non-login"
  shell: "awk -F: '($3 < {{ rhel8cis_rule_5_5_2_min_uid }}) {print $1 }' /etc/passwd"
  changed_when: no
  check_mode: no
  register: system_account
  when:
    - rhel8cis_rule_5_5_2|bool
  tags:
    - level1
    - level2
    - patch
    - rule_5.5.2

- name: "SCORED | 5.5.3 | PATCH | Ensure default user shell timeout is 900 seconds or less"
  command: /bin/true
  changed_when: no
  when:
    - rhel8cis_rule_5_5_3|bool
  tags:
    - level1
    - level2
    - patch
    - rule_5.5.3
    - notimplemented

- name: "SCORED | 5.5.4 | PATCH | Ensure default group for the root account is GID 0"
  command: usermod -g 0 root
  changed_when: no
  failed_when: no
  when:
    - rhel8cis_rule_5_5_4|bool
  tags:
    - level1
    - level2
    - patch
    - rule_5.5.4

- name: "SCORED | 5.5.5 | PATCH | Ensure default user umask is 027 or more restrictive"
  block:
    - name: "SCORED | 5.5.5 | PATCH | Ensure default user umask is 027 or more restrictive - /etc/bashrc"
      replace:
        path: /etc/bashrc
        regexp: '(^\s+umask) 002'
        replace: '\1 027'

    - name: "SCORED | 5.5.5 | PATCH | Ensure default user umask is 027 or more restrictive - /etc/profile"
      replace:
        path: /etc/profile
        regexp: '(^\s+umask) 002'
        replace: '\1 027'
  when:
      - rhel8cis_rule_5_5_5|bool
  tags:
      - level1
      - level2
      - patch
      - rule_5.5.5

- name: "NOTSCORED | 5.6 | PATCH | Ensure root login is restricted to system console"
  command: /bin/true
  changed_when: no
  when:
    - rhel8cis_rule_5_6|bool
  tags:
    - level1
    - level2
    - patch
    - rule_5.6
    - notimplemented

- name: "SCORED | 5.7 | PATCH | Ensure access to the su command is restricted"
  lineinfile:
    state: present
    dest: /etc/pam.d/su
    regexp: '^(#)?auth\s+required\s+pam_wheel\.so'
    line: 'auth           required        pam_wheel.so use_uid'
  when:
    - rhel8cis_rule_5_7|bool
  tags:
    - level1
    - level2
    - patch
    - rule_5.7

- name: "SCORED | 5.7 | PATCH | Ensure access to the su command is restricted - wheel group contains root"
  user:
    name: root
    groups: wheel
  when:
    - rhel8cis_rule_5_7|bool
  tags:
    - level1
    - level2
    - patch
    - rule_5.7
